=== Lordfirespeed/NuGet-GameLib-Dehumidifier/assets/game-version.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "title": "Game Version Entry",
  "description": "Metadata for a particular game version.",
  "type": "object",
  "properties": {
    "buildId": {
      "title": "Build ID",
      "description": "Steam build ID",
      "type": "integer"
    },
    "timeUpdated": {
      "title": "Time Updated",
      "type": "integer"
    },
    "gameVersion": {
      "title": "Game Version",
      "$ref": "semver.schema.json"
    },
    "depots": {
      "title": "Version Depot Metadata Mapping",
      "description": "Entries that provide distribution depot metadata for this game version",
      "type": "array",
      "items": {
        "title": "Version Depot Metadata Entry",
        "type": "object",
        "properties": {
          "depotId": {
            "title": "Steam Depot ID",
            "type": "integer"
          },
          "manifestId": {
            "title": "Steam Manifest ID",
            "description": "Manifest ID of the depot's contents on the 'public' branch for this game version",
            "type": "integer"
          }
        },
        "required": ["depotId", "manifestId"]
      }
    },
    "frameworkTargets": {
      "title": "Framework targets",
      "description": "Entries that map NuGet package Target Framework Moniker to package dependencies under that framework.",
      "type": "array",
      "items": {
        "title": "Framework target",
        "description": "Entry associating a TFM with some NuGet package dependencies.",
        "type": "object",
        "properties": {
          "tfm": {
            "title": "Target Framework Moniker",
            "$ref": "dotnet-target-framework-moniker.schema.json"
          },
          "dependencies": {
            "title": "Dependencies",
            "description": "List of NuGet package dependency specifiers",
            "type": "array",
            "items": {
              "title": "NuGet dependency",
              "description": "NuGet package dependency specifier",
              "type": "object",
              "properties": {
                "name": {
                  "title": "Name",
                  "description": "NuGet package dependency package name",
                  "type": "string"
                },
                "version": {
                  "title": "Version",
                  "$ref": "semver.schema.json"
                }
              },
              "required": [ "name", "version" ]
            }
          }
        },
        "required": [ "tfm", "dependencies" ]
      },
      "minItems": 1
    }
  },
  "required": [ "buildId", "gameVersion", "timeUpdated", "depots", "frameworkTargets" ]
}

=== Lordfirespeed/NuGet-GameLib-Dehumidifier/Games/valheim/versions/13920841.json
{
  "buildId": 13920841,
  "timeUpdated": 1712748365,
  "gameVersion": "0.217.46",
  "depots": [
    {
      "depotId": 892972,
      "manifestId": 3694758505878885183
    },
    {
      "depotId": 892971,
      "manifestId": 1036124488433202120
    }
  ],
  "frameworkTargets": [
    {
      "tfm": "netstandard2.0",
      "dependencies": [
        {
          "name": "UnityEngine.Modules",
          "version": "2022.3.12"
        }
      ]
    }
  ]
}

=== Lordfirespeed/NuGet-GameLib-Dehumidifier/Games/dyson-sphere-program/versions/13021605.json
{
  "buildId": 13021605,
  "timeUpdated": 1703172315,
  "gameVersion": "0.10.28-r21014",
  "depots": [
    {
      "depotId": 1366541,
      "manifestId": 3700818433573659132
    }
  ],
  "frameworkTargets": [
    {
      "tfm": "netstandard2.0",
      "dependencies": [
        {
          "name": "UnityEngine.Modules",
          "version": "2018.4.12"
        }
      ]
    }
  ]
}

=== Lordfirespeed/NuGet-GameLib-Dehumidifier/Games/lethal-company/versions/12922815.json
{
  "buildId": 12922815,
  "timeUpdated": 1702209853,
  "gameVersion": "45.0.2",
  "depots": [
    {
      "depotId": 1966721,
      "manifestId": 7637156099460715726
    }
  ],
  "frameworkTargets": [
    {
      "tfm": "netstandard2.0",
      "dependencies": [
        {
          "name": "UnityEngine.Modules",
          "version": "2022.3.9"
        },
        {
          "name": "Newtonsoft.JSON",
          "version": "13.0.3"
        }
      ]
    }
  ]
}

=== Lordfirespeed/NuGet-GameLib-Dehumidifier/Games/risk-of-rain-2/versions/17431597.json
{
  "buildId": 17431597,
  "timeUpdated": 1741118273,
  "gameVersion": "",
  "depots": [
    {
      "depotId": 632361,
      "manifestId": 6971805131910532689
    }
  ],
  "frameworkTargets": [
    {
      "tfm": "netstandard2.0",
      "dependencies": [
        {
          "name": "UnityEngine.Modules",
          "version": "2019.4.26"
        }
      ]
    }
  ]
}

=== Lordfirespeed/NuGet-GameLib-Dehumidifier/Games/content-warning/versions/16750464.json
{
  "buildId": 16750464,
  "timeUpdated": 1734264100,
  "gameVersion": "",
  "depots": [
    {
      "depotId": 2881651,
      "manifestId": 4763499704581700907
    }
  ],
  "frameworkTargets": [
    {
      "tfm": "netstandard2.1",
      "dependencies": [
        {
          "name": "UnityEngine.Modules",
          "version": "2022.3.10"
        },
        {
          "name": "Newtonsoft.JSON",
          "version": "13.0.3"
        },
        {
          "name": "WebSocketSharp",
          "version": "1.0.3-rc11"
        }
      ]
    }
  ]
}

=== Lordfirespeed/NuGet-GameLib-Dehumidifier/Games/content-warning/versions/14020941.json
{
  "buildId": 14020941,
  "timeUpdated": 1712830309,
  "gameVersion": "0.1.9-b",
  "depots": [
    {
      "depotId": 2881651,
      "manifestId": 4621153643729368338
    }
  ],
  "frameworkTargets": [
    {
      "tfm": "netstandard2.1",
      "dependencies": [
        {
          "name": "UnityEngine.Modules",
          "version": "2022.3.10"
        },
        {
          "name": "Newtonsoft.JSON",
          "version": "13.0.3"
        },
        {
          "name": "WebSocketSharp",
          "version": "1.0.3-rc11"
        }
      ]
    }
  ]
}
